twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']
   # globals:
      #  categories: '@App\controller\NavController'
    paths:
        '%kernel.project_dir%/public/css' : styles

when@test:
    twig:
        strict_variables: true
