when@dev:
    web_profiler:
        toolbar: true
        intercept_redirects: false

    framework:
        profiler:
            only_exceptions: false
            collect_serializer_data: true

when@test:
    web_profiler:
        toolbar: false
        intercept_redirects: false  #Arret des mails et récupérations dans la débug toolbar de symfony

    framework:
        profiler: { collect: false }
